<?php

namespace AppBundle\Repository;

/**
 * LikesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikesRepository extends \Doctrine\ORM\EntityRepository
{

	public function getMyFavoriteShops($user,$status = null)
    {
    	    $userLat = $user->getUserinfo()->getLat();
            $userLang = $user->getUserinfo()->getLang();
            $query = $this->createQueryBuilder('a');
               $query->where('a.user = :user');
               if ($status != null) {
               	$query->andWhere('a.'.$status.' = 1');
               }
               
               $query->setParameter('user', $user->getId());
               $query->orderBy('a.id', 'DESC');
               $likes = $query->getQuery()->getResult();

               $results = array();

             foreach ($likes as $like) {
                if ($userLat != null && $userLang != null) {
                    $like->getShops()->setDistance($this->getDistance($like->getShops()->getLat(),$like->getShops()->getLang(),$userLat,$userLang)) ;
                }
                       $results[] = $like;
                                   
             }
             return $results;
    }

    private function getDistance($lat1, $lon1, $lat2, $lon2) {

      $theta = $lon1 - $lon2;
      $dist = sin(deg2rad($lat1)) * sin(deg2rad($lat2)) +  cos(deg2rad($lat1)) * cos(deg2rad($lat2)) * cos(deg2rad($theta));
      $dist = acos($dist);
      $dist = rad2deg($dist);
      $miles = $dist * 60 * 1.1515;
      

     
        return round($miles * 1.609344,2);
      
    }   
}
