# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                check_path: /login_check
                # login success redirecting options (read further below)
                always_use_default_target_path: false
                default_target_path:            fos_user_profile_show
                target_path_parameter:          _target_path


            logout:       
                # handlers: [mybundle_logoutlistener]
                target: fos_user_security_login
            anonymous:    true
            switch_user: true
            # switch_user:
            #     provider:             ~
            #     parameter:            _switch_user
            #     role:                 ROLE_ALLOWED_TO_SWITCH
            remember_me:
                secret: "%secret%"
                lifetime: 360000 # in seconds
                remember_me_parameter: _remember_me

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/shops/, role: ROLE_USER }
        - { path: ^/category/, role: ROLE_USER }
        - { path: ^/location/, role: ROLE_USER }
